[package]
name = "stanza-server"
version = "0.1.0"
authors = ["Seth Samuel <sethfsamuel@gmail.com>"]

[dependencies.iron]
version = "*"
default-features = false

[dependencies]
rustc-serialize = "0.3"