[package]
name = "stanza-server"
version = "0.1.0"
authors = ["Seth Samuel <sethfsamuel@gmail.com>"]

[dependencies.iron]
version = "*"

[dependencies]
rustc-serialize = "0.3"

[dependencies.hyper]
version = "0.7.2"
